### ISSUE TITLE
User Story: Create Database

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#10]
Epic 3: #9 

As a developer I want to create the websites database and add products

Tasks

- [x] Create Django Database
- [x] Connect website and Database
- [x] Create model
- [x] Add data to the Database
- [x] Add images 

Acceptance Criteria

- Database is created
- Database is connected to the website
