### ISSUE TITLE
 User Story: Create products page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#11]
Epic 3: #9

As a user, I want to see the products page clearly so that it is easy to find products.

Tasks:

- [x] Create products page
- [x]  Set URL arguments
- [x] Display products 
- [x] Create a view on the website for the data

Acceptance Criteria:

- User can open the products page.
- User can view an error message if there is a 404 response.
- User can see images.
- User can see content that has been added.
- Data can be display from the database on the website
