### ISSUE TITLE
User Story: Create product filters

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#14]
Epic 4: #13 

As a user, I want to be able to filter products on the products page so that I can find what I am looking for.

Tasks:

- [x] Create keyword search functions
- [x] Create  category filtering functions
- [x] Display the filtered products

Acceptance Criteria:

 - User can search for products
 - User can see a list of displayed products after filtering
