### ISSUE TITLE
User Story: Create basket

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#16]
Epic 5: #17 

As a user I want to be able to add items to my shopping basket so that I can see what is in the basket.

Task

- [x] Create quantity selection input in detail's page
- [x] Create add button in detail's page
- [x] Create Checkout App
- [x] Create basket page
- [x] Create total price section in basket page
- [x] Create delivery charge section in basket page
- [x] Create all related functionality 

Acceptance criteria  

- User can add products from details page
- User can see the basket page
- User can see the items they selected in the basket
- User can see the total price
- User can see the delivery cost
