### ISSUE TITLE
 User Story: Create checkout section

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#18]
Epic 5 #17 

As a user I want to be able to check out easily also can check the total price before click the button

Task

- [x] Create a price section in a basket page
- [x] Display all the calculation for the shopping
- [x] Display delivery cost
- [x] Create functionality 
- [x] Create checkout button

Acceptance criteria

User can see the total price of shopping
User can see the the delivery fee
