### ISSUE TITLE
User Story: Create the project structure

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#2]
Epic #1 

As a Developer, I want to create the project structure so I can develop the Hair Experts website

 Tasks:

- [x] Create a new project
- [x] Install Django
- [x] Create a new app
- [x] Set up all basic features in settings
- [x] Install required modules 
- [x] Create the projects .env and store the secret key
- [x] Set up Allauth
- [x] Set up base template

Acceptance Criteria:

- The structure for the Frontend and Backend of the project are created
- All require basic functionality has been added.
