### ISSUE TITLE
User Story: Create Toast for website

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#21]
Epic 6: #20 

As a user, I want to see a notification when I add, update and delete item to the shopping basket so I see what is in the basket

- [x] Create the toast success message
- [x] Create the toast error message
- [x] Create the toast info message
- [x] Create the toast warning message
- [x] Create item details in the notification box
- [x] Create total price display
- [x] Create a payment button
- [x] Add function to display toasts

Acceptance Criteria:

- When a user adds an item they will see a notification pop up on the screen
- When a user update an item they will see a notification pop up on the screen
- When a user delete an item they will see a notification pop up on the screen
- User can see items in the basket
- User can see total price in the basket 
- User can a click payment from the notification box
