### ISSUE TITLE
 User Story: Create checkout app

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#24]
Epic 7: #22

As a user, I want to fill out my information so that they can send my order 

- [x] Create a view for the page
- [x] Create a shopping form
- [x] Display order items
- [x] Create functionality

Acceptance Criteria:

- User can see the shopping form
- User can fill out the shopping form
- User can see order items
