### ISSUE TITLE
User Story: Have a personalized user profile

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#28]
Epic 8: #27 

As a user, I want to have a personalized user profile so that I can check my order history, confirmation, and payment information.

- [x] Create profile app
- [x] Create model for user profile
- [x] Create a page and set up display
- [x] Update webhook for profile

Acceptance Criteria:

- User can see the account information
- User can check their order history
- User can see success message when making an order
