### ISSUE TITLE
User Story: Create Admin Profiles for website

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#31]
Epic 9 #30 

As an owner I want to have add, edit and delete functionality for the site items to manage stock. 

- [x] Create a form.py for product form 
- [x] Create View for the store owners to add, edit and delete page
- [x] Create functions for Add.
- [x] Create functions for Edit.
- [x] Create functions for Delete.

Acceptance Criteria

- The owners of the site can log in and use their Admin rights to Add, Edit and Delete items for them website.
