### ISSUE TITLE
User Story: News page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#33]
Epic 10: #32 

As a site owner, I want to have a news section so that I can inform customers about upcoming news

* [x] Create a news app
* [x] Create model
* [x] Add news in the database
* [x] Create view and URL
* [x] Create news page

Acceptance Criteria:
- User can open the news page 
- User can read the news  and see information about the site
