### ISSUE TITLE
User Story: Update News Page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#34]
Epic 10: #32 

As an Admin I want to Add, Edit and Delete News articles on the sites news page so that I can keep it updated

- [x] Create the Add new function
- [x] Create the Edit news function
- [x] Create the Delete news function

Acceptance criteria

- Admin can be keep updated about the site.  
- Admin can add news
- Admin can edit news
- Admin can delete news
