### ISSUE TITLE
 User Story: Final Touch

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#36]
Epic 12: #38  

As a developer I want to check and finalize this website so that I can complete this site

- [x] Check and fix code
- [x] Check and fix responsiveness 
- [x] Check and fix spelling 
- [x] Check and fix error 
- [x] Test the site
- [x] 404 page
- [x] Email set up
- [x] Connect bot
- [x] Site xml 
- [x] Read Me

Acceptance criteria
- User can see customized 404 page
- User can get email
- Now website is ready to go
