### ISSUE TITLE
User Story: Create home page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#4]
As a user, I want to be able to open the home page and understand what is this website for.

 Tasks:

- [x] Create the home app 
- [x] Set up the home page
- [x] Create the page structure
- [x] Create the header 
- [x] Add a leading message

Acceptance Criteria:

- User opens landing page 
- User understand what this website for
