### ISSUE TITLE
User Story: Add News letter

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/the-hair-experts#41]
Epic 12: #38 

As a user I want to be able to subscribe to a news letter so that I can stay up to date with the latest news and offers.

- [x] Create news letter app
- [x] Create news letter views
- [x] Create news letter URL's
- [x] Create news letter forms
- [x] Set up with mail chimp

Acceptance criteria

- User can subscribe to a news letter
